# Generated by Django 4.2.30 on 2026-10-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('edited_events', models.PositiveIntegerField(default=0)),
                ('cancelled_events', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Bot Statistics',
                'ordering': ['-date'],
            },
        ),
    ]
