# Generated by Django 4.2.30 on 2026-10-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_botstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название встречи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('organizer_id', models.BigIntegerField(verbose_name='ID организатора')),
                ('organizer_name', models.CharField(blank=True, max_length=255, verbose_name='Имя организатора')),
                ('participant_id', models.BigIntegerField(verbose_name='ID участника')),
                ('participant_name', models.CharField(blank=True, max_length=255, verbose_name='Имя участника')),
                ('status', models.CharField(choices=[('pending', 'Ожидается'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
