# Generated by Django 4.2.30 on 2026-10-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_telegramuser_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
